---
AWSTemplateFormatVersion: 2010-09-09
Description: IntSiteCallerECRRepositoryCreate

Resources:
  IntSiteCallerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: intsitecaller
      Tags:
        - Key: "Name"
          Value: "intsitecaller"

Outputs:
  Arn:
    Value: !GetAtt IntSiteCallerECRRepository.Arn

# aws cloudformation create-stack --stack-name IntSiteCallerECRRepositoryCreate --template-body file://repository.yml  --profile=<your_profile> --region=us-east-1 --capabilities CAPABILITY_NAMED_IAM;

# aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 483158796244.dkr.ecr.us-east-1.amazonaws.com
#